export const TYPESCRIPT_SEMANTIC_TOKEN_SPIKE_FIXTURE = [
    "function sealed(value: Function) { return value; }",
    "",
    "@sealed",
    "export class Repository<TItem extends { readonly id: string }> {",
    "    public static readonly kind = \"repository\";",
    "    public readonly items: TItem[] = [];",
    "",
    "    public async findById(id: string): Promise<TItem | undefined> {",
    "        return this.items.find((item) => item.id === id);",
    "    }",
    "}",
    "",
    "export interface Service<TRequest, TResponse> {",
    "    execute(request: TRequest): Promise<TResponse>;",
    "}",
    "",
    "export enum Status {",
    "    Idle = \"idle\",",
    "    Ready = \"ready\",",
    "}",
    "",
    "export namespace Domain {",
    "    export type Entity<T> = T & { readonly id: string };",
    "}",
].join("\n");

export const MONACO_TYPESCRIPT_SEMANTIC_TOKEN_TYPES = [
    "class",
    "decorator",
    "enum",
    "enumMember",
    "function",
    "interface",
    "method",
    "namespace",
    "parameter",
    "property",
    "type",
    "typeParameter",
    "variable",
] as const;

export const MONACO_TYPESCRIPT_SEMANTIC_TOKEN_MODIFIERS = [
    "async",
    "declaration",
    "defaultLibrary",
    "deprecated",
    "readonly",
    "static",
] as const;

export const MONACO_TYPESCRIPT_SEMANTIC_TOKEN_SELECTORS = [
    "class",
    "class.defaultLibrary",
    "class.deprecated",
    "decorator",
    "enum",
    "enumMember",
    "function",
    "function.async",
    "function.defaultLibrary",
    "interface",
    "interface.defaultLibrary",
    "method",
    "method.async",
    "method.defaultLibrary",
    "method.static",
    "namespace",
    "parameter",
    "property",
    "property.defaultLibrary",
    "property.deprecated",
    "property.readonly",
    "property.static",
    "type",
    "type.defaultLibrary",
    "typeParameter",
    "variable",
    "variable.defaultLibrary",
    "variable.deprecated",
    "variable.readonly",
] as const;

export const MONACO_TYPESCRIPT_SEMANTIC_TOKEN_AUDIT = {
    fixture: TYPESCRIPT_SEMANTIC_TOKEN_SPIKE_FIXTURE,
    modifiers: MONACO_TYPESCRIPT_SEMANTIC_TOKEN_MODIFIERS,
    notes: [
        "Monaco 0.55 loads the semantic token editor contribution in standalone mode.",
        "Comando registers a document semantic token provider backed by the TypeScript worker's getEncodedSemanticClassifications. See monacoSemanticTokensProvider.ts.",
        "When the bundled Monaco TypeScript worker adapter does not surface getEncodedSemanticClassifications at runtime (the method exists on the underlying languageService but is not proxied in upstream 0.55), the provider degrades to an empty token set so TextMate highlighting remains the single source of truth.",
        "These selectors are the effective Monaco theme selectors consumed by the provider above.",
    ],
    selectors: MONACO_TYPESCRIPT_SEMANTIC_TOKEN_SELECTORS,
    tokenTypes: MONACO_TYPESCRIPT_SEMANTIC_TOKEN_TYPES,
} as const;
