export const IPC_CHANNELS = {
    getBootstrapSnapshot: "app:get-bootstrap-snapshot",
    getPersistenceSnapshot: "app:get-persistence-snapshot",
    getSettingsSnapshot: "settings:get-snapshot",
    saveCodexRuntimeSettings: "settings:save-codex-runtime-settings",
    getSystemTheme: "app:get-system-theme",
    saveSettingsSnapshot: "settings:save-snapshot",
    saveActiveProjectId: "app:save-active-project-id",
    listProjects: "projects:list",
    openProjects: "projects:open",
    addProjectPaths: "projects:add-paths",
    removeProject: "projects:remove",
    touchProject: "projects:touch",
    listProjectTree: "projects:list-tree",
    openProjectFile: "projects:open-file",
    saveProjectFile: "projects:save-file",
    createProjectEntry: "projects:create-entry",
    renameProjectEntry: "projects:rename-entry",
    deleteProjectEntry: "projects:delete-entry",
    revealProjectEntry: "projects:reveal-entry",
    searchProjectEntries: "projects:search-entries",
    getWorkspaceSnapshot: "workspace:get-snapshot",
    saveWorkspaceSnapshot: "workspace:save-snapshot",
    getChatSessionState: "workspace:get-chat-session-state",
    createTerminalSession: "terminals:create-session",
    writeTerminalInput: "terminals:write-input",
    resizeTerminalSession: "terminals:resize-session",
    closeTerminalSession: "terminals:close-session",
    getAiRuntimeStatus: "ai:get-runtime-status",
    getAiSessionSnapshot: "ai:get-session-snapshot",
    sendAiPrompt: "ai:send-prompt",
    cancelAiSession: "ai:cancel-session",
    closeAiSession: "ai:close-session",
    respondAiPermission: "ai:respond-permission",
    keepAiTrackedFile: "ai:keep-tracked-file",
    rejectAiTrackedFile: "ai:reject-tracked-file",
    keepAllAiTrackedFiles: "ai:keep-all-tracked-files",
    rejectAllAiTrackedFiles: "ai:reject-all-tracked-files",
};
export const IPC_EVENTS = {
    projectTreeInvalidated: "projects:tree-invalidated",
    themeUpdated: "app:theme-updated",
    terminalData: "terminals:data",
    terminalExit: "terminals:exit",
    aiRuntimeStatus: "ai:runtime-status",
    aiSessionSnapshot: "ai:session-snapshot",
};
